CREATE DATABASE IF NOT EXISTS mvc_food
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;

USE mvc_food;

CREATE TABLE IF NOT EXISTS orders (
  id INT AUTO_INCREMENT PRIMARY KEY,
  user_id VARCHAR(64) NOT NULL,
  user_name VARCHAR(80) NOT NULL,
  dish_name VARCHAR(120) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);




